export enum WsTopicEnum {
  MARKET_TICKER = '/market/ticker:',
  MARKET_TICKER_ALL = '/market/ticker:all',
  MARKET_SNAPSHOT = '/market/snapshot:',
  MARKET_LEVEL2 = '/market/level2:',
  STOP_MARKET_LEVEL2_DEPTH5 = '/spotMarket/level2Depth5:',
  STOP_MARKET_LEVEL2_DEPTH50 = '/spotMarket/level2Depth50:',
  MARKET_CANDLES = '/market/candles:',
  MARKET_MATCH = '/market/match:',
  INDICATOR_INDEX = '/indicator/index:',
  INDICATOR_MARK_PRICE = '/indicator/markPrice:',
  MARGIN_FUNDING_BOOK = '/margin/fundingBook:',
  SPOT_MARKET_TRADE_ORDERS = '/spotMarket/tradeOrders',
  ACCOUNT_BALANCE = '/account/balance',
  MARGIN_POSITION = '/margin/position',
  MARGIN_LOAN = '/margin/loan:',
  SPOT_MARKET_ADVANCED_ORDERS = '/spotMarket/advancedOrders',
}
